# Generated by Django 3.0.5 on 2020-05-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Your comments here ...', max_length=3000),
        ),
    ]
